---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tlowerison/standard-base.name" $ }}
  labels: {{ include "tlowerison/standard-base.labels" $ | nindent 4 }}{{ if hasKey .Values "annotations" }}
  annotations: {{ include "tlowerison/standard-base.yaml" .Values.annotations | nindent 4 }}{{ end }}
spec:
  replicas: {{ .Values.replicas }}
  selector: {{ include "tlowerison/standard-base.selector" $ | nindent 4 }}
  template:
    metadata:
      labels: {{ include "tlowerison/standard-base.labels" $ | nindent 8 }}{{ if hasKey .Values "annotations" }}
      annotations: {{ include "tlowerison/standard-base.yaml" .Values.annotations | nindent 8 }}{{ end }}
    spec: {{ include "tlowerison/standard-base.pod" $ | nindent 6 -}}
