{{$name := .Values.global.name}}
{{required "global.name is required" $name}}
{{$env := .Values.global.environment}}
{{required "global.environment is required" $env}}
{{$selectors := dict "name" $name "chartName" .Chart.Name "env" $env "tier" .Values.tier}}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{include "secretName" $selectors}}
