apiVersion: v1
entries:
  standard-cronjob:
  - apiVersion: v1
    created: "2021-03-07T19:36:35.469115-08:00"
    digest: 12c1bd1ae7e12c47472221c7723d41076c2e0c0ca4e65255e6c810aaadd76762
    maintainers:
    - email: tlowerison@tuta.io
      name: Trey Lowerison
    name: standard-cronjob
    urls:
    - https://github.com/tlowerison/helm/releases/download/1.0.0/standard-cronjob-1.0.0.tgz
    version: 1.0.0
generated: "2021-03-07T19:36:35.46866-08:00"
